export const BRAND_EN = "JJ Signature"
export const BRAND_SUBTITLE = 'JJ Signature'
export const BRAND_LOGO = '/logo.png'

export const BRAND_PRIMARY_PHONE_DISPLAY = '+91 63790 48966'
export const BRAND_PRIMARY_PHONE_E164 = '916379048966'
export const BRAND_SECONDARY_PHONE_DISPLAY = '+91 63790 48966'
export const BRAND_SECONDARY_PHONE_E164 = '916379048966'
export const BRAND_THIRD_PHONE_DISPLAY = BRAND_PRIMARY_PHONE_DISPLAY
export const BRAND_THIRD_PHONE_E164 = BRAND_PRIMARY_PHONE_E164
export const BRAND_PHONE_DISPLAY = BRAND_PRIMARY_PHONE_DISPLAY
export const BRAND_PHONE_E164 = BRAND_PRIMARY_PHONE_E164
export const BRAND_WHATSAPP = BRAND_THIRD_PHONE_DISPLAY
export const WHATSAPP_NUM = BRAND_THIRD_PHONE_E164
export const BRAND_WHATSAPP_LINK = `https://wa.me/${BRAND_THIRD_PHONE_E164}`
export const BRAND_EMAIL = 'safasignora@gmail.com'
export const BRAND_ADDRESS = '31 A, Blue Star Building, Madurai Road Junction, Tirunelveli - 627001'
export const BRAND_LOCATION_LINK = '#'
